version: "3.16"

services:
  download-mirror:
    image: ghcr.io/gpu-ninja/download-mirror:latest
    environment:
      - DOMAIN=koopt.sh
      - EMAIL=damian@pecke.tt
      - TOKEN_FILE=/run/secrets/upload_token
      - CACHE=/var/www/.blobs
      - WEBDAV_URI=https://<username>.your-storagebox.de
      - WEBDAV_USER=<username>
      - WEBDAV_PASSWORD_FILE=/run/secrets/webdav_password
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - autotls-cache:/var/www/.cache
      - blob-cache:/var/www/.blobs
    secrets:
      - upload_token
      - webdav_password
    restart: always

  loopy-dns:
    image: ghcr.io/gpu-ninja/loopy-dns:latest
    command:
      - --zone=local.koopt.sh.
    ports:
      - "53:5353/udp"
    restart: always

volumes:
  autotls-cache:
  blob-cache:

secrets:
  upload_token:
    file: upload_token.txt
  webdav_password:
    file: webdav_password.txt